set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreadedDLL)
set(CMAKE_TRY_COMPILE_CONFIGURATION Release)
find_program(AQT_CLANG NAMES clang-cl-20 clang-20 clang-cl REQUIRED)
file(MAKE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/../.build-deps/bin")
file(CREATE_LINK "${AQT_CLANG}" "${CMAKE_CURRENT_LIST_DIR}/../.build-deps/bin/clang-cl" SYMBOLIC)
set(CMAKE_C_COMPILER "${CMAKE_CURRENT_LIST_DIR}/../.build-deps/bin/clang-cl")
set(CMAKE_CXX_COMPILER "${CMAKE_C_COMPILER}")
find_program(CMAKE_LINKER NAMES lld-link-20 lld-link REQUIRED)
find_program(CMAKE_AR NAMES llvm-lib-20 llvm-lib REQUIRED)
find_program(CMAKE_RC_COMPILER NAMES llvm-rc-20 llvm-rc REQUIRED)
find_program(CMAKE_MT NAMES llvm-mt-20 llvm-mt REQUIRED)

if(NOT DEFINED XWIN_SYSROOT)
    set(XWIN_SYSROOT "$ENV{XWIN_SYSROOT}")
endif()
if(NOT XWIN_SYSROOT)
    message(FATAL_ERROR "Set XWIN_SYSROOT to the xwin sysroot directory")
endif()
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES XWIN_SYSROOT)
set(CMAKE_C_FLAGS_INIT "--target=x86_64-pc-windows-msvc /winsysroot\"${XWIN_SYSROOT}\"")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} /EHsc")
set(CMAKE_EXE_LINKER_FLAGS_INIT "/winsysroot:\"${XWIN_SYSROOT}\"")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT}")
set(CMAKE_RC_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
